[RELENG-4725] Add github sso autentication to nginx
scality/artifacts pull request #5
Opened 2021-07-16 08:42 UTC by erwan-b

2021-07-16 08:42 UTC, bert-e commented
# Hello erwan-b,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/artifacts/bert-e/doc/user).





*Status report is not available.*

2021-07-16 08:42 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer

2021-07-16 09:05 UTC, bertranddemiddelaer commented on lua/github_access.lua
> +   return ngx.exit(ngx.HTTP_OK)
HTTP_OK ? Did not you want HTTP_UNAUTHORIZED instead ?

2021-07-16 09:05 UTC, bertranddemiddelaer commented on lua/github_access.lua
> +   return ngx.exit(ngx.HTTP_OK)
Did you mean HTTP_FORBIDDEN ?

2021-07-16 09:05 UTC, bertranddemiddelaer commented on lua/github_access.lua
> +    local res =  ngx.location.capture("/force_external_request/orgs/scality/members/" .. username)
s/external/github/ no ?

2021-07-16 09:05 UTC, bertranddemiddelaer commented on lua/github_access.lua
> +local b64 = require "ngx.base64"
Not sure it is needed. Seems like dead code.

2021-07-16 09:51 UTC, bertranddemiddelaer commented on lua/github_access.lua
> +    local password = auth:sub(divider+1)
This variable is not used anywhere ?

2021-07-16 14:25 UTC, bertranddemiddelaer reviewed
This PR needs to change tests to prove that auth is working. Good news is that right now, unmodified tests show that the client that does not provide any credentials sees its access refused.

2021-07-16 15:36 UTC, tcarmet requested changes
Overall the lua code and what we're doing here looks more than good to me.

However I would add a couple of requirements.
* I should be able to deactivate or activate this setting. It should not be mandatory. I want to be able to run artifacts on my local machine without requiring it to set it up with github auth.
* Let's not hardcode the organization we are checking in the code, and set a proper variable to set this up.

On a side note: Do not forget to update the helm chart accordingly with the new settings if required

2021-07-16 15:36 UTC, tcarmet commented on lua/github_access.lua
> +    local res =  ngx.location.capture("/force_github_request/orgs/scality/members/" .. username)
scality org should not be hardcoded and should rather be a variable.

2021-07-16 15:36 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer






The following reviewers are expecting changes from the author, or must review again:

* @tcarmet

2021-07-19 20:34 UTC, tcarmet requested changes
Thanks for applying my comment! It's looking good.

The last thing I see would be to update the helm chart in order to be able to set the new variables in Artifacts' runtime.
Check `helm/charts/artifacts`

2021-07-20 09:17 UTC, erwan-b commented
`It seems that authentication from client point of view is being done via a header, where today in artifacts it's being done via basic auth. Can you confirm to me that we are still able to login via basic auth? Some clients like apt/yum will require it. @bertranddemiddelaer I'll let you check that with @erwan-b (After re reading the code I think it's already implemented, so I'm probably mistaken here, but could you please double check heart )
`

Basic auth is done by header :+1:

2021-07-20 12:54 UTC, bert-e commented
# Conflict




There is a conflict between your branch `feature/RELENG-4725/github-sso-authentication` and the
destination branch `development/4.0`.

Please resolve the conflict on **the feature branch** (`feature/RELENG-4725/github-sso-authentication`).

```sh
git fetch && \
git checkout origin/feature/RELENG-4725/github-sso-authentication && \
git merge origin/development/4.0
```

Resolve merge conflicts and commit

```sh
git push origin HEAD:feature/RELENG-4725/github-sso-authentication
```

2021-07-20 12:56 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer






The following reviewers are expecting changes from the author, or must review again:

* @tcarmet

2021-07-20 14:31 UTC, tcarmet reviewed
Last comment, those variables do not belong in the cloudstorage section. Cloudstorage is meant for communication with S3 buckets.

2021-07-20 14:31 UTC, tcarmet commented on charts/artifacts/templates/secrets.yaml
> +  GITHUB_API_ENABLED: {{ .Values.cloudStorage.githubApiEnabled | b64enc | quote }}
```suggestion
  GITHUB_API_URL: {{ .Values.githubApiUrl | b64enc | quote }}
  GITHUB_API_COMPANY: {{ .Values.githubApiCompany | b64enc | quote }}
  GITHUB_API_ENABLED: {{ .Values.githubApiEnabled | b64enc | quote }}
```

2021-07-20 14:31 UTC, tcarmet commented on charts/artifacts/values.yaml
> +
```suggestion
## githubApiUrl contains the api url to check the auth connection
##
githubApiUrl: 'https://api.github.com'

## githubApiCompany The github company to check the user is in
##
githubApiCompany: ''

## githubApiEnabled set the github basic auth check enabled or not
##
githubApiEnabled: 'true'
```

2021-07-20 15:05 UTC, tcarmet approved these changes

2021-07-20 15:05 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* one peer

2021-07-20 15:22 UTC, erwan-b commented
/approve

2021-07-20 15:22 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/4.0`



The following branches will **NOT** be impacted:

* `development/2.0`
* `development/3.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-07-20 15:22 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/4.0`



The following branches have **NOT** changed:

* `development/2.0`
* `development/3.0`



Please check the status of the associated issue RELENG-4725.

Goodbye erwan-b.

2021-07-20 15:23 UTC, merged